urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url

from pybb.defaults import PYBB_NICE_URL
from pybb.feeds import LastPosts, LastTopics
from pybb.views import IndexView, CategoryView, ForumView, TopicView, \
    AddPostView, EditPostView, MovePostView, UserView, PostView, ProfileEditView, \
    DeletePostView, StickTopicView, UnstickTopicView, CloseTopicView, \
    OpenTopicView, ModeratePost, TopicPollVoteView, LatestTopicsView, \
    UserTopics, UserPosts, topic_cancel_poll_vote, block_user, unblock_user, \
    delete_subscription, add_subscription, post_ajax_preview, \
    mark_all_as_read, ForumSubscriptionView, UserEditPrivilegesView

app_name = 'pybbm'

urlpatterns = [
    # Syndication feeds
    url('^feeds/posts/$', LastPosts(), name='feed_posts'),
    url('^feeds/topics/$', LastTopics(), name='feed_topics'),
]

urlpatterns += [
    # Index, Category, Forum
    url('^$', IndexView.as_view(), name='index'),
    url('^category/(?P<pk>\d+)/$', CategoryView.as_view(), name='category'),
    url('^forum/(?P<pk>\d+)/$', ForumView.as_view(), name='forum'),

    # User
    url('^users/(?P<username>[^/]+)/$', UserView.as_view(), name='user'),
    url('^block_user/([^/]+)/$', block_user, name='block_user'),
    url('^unblock_user/([^/]+)/$', unblock_user, name='unblock_user'),
    url(r'^users/(?P<username>[^/]+)/topics/$', UserTopics.as_view(),
        name='user_topics'),
    url(r'^users/(?P<username>[^/]+)/posts/$', UserPosts.as_view(),
        name='user_posts'),
    url(r'^users/(?P<username>[^/]+)/edit-privileges/$',
        UserEditPrivilegesView.as_view(), name='edit_privileges'),

    # Profile
    url('^profile/edit/$', ProfileEditView.as_view(), name='edit_profile'),

    # Topic
    url('^topic/(?P<pk>\d+)/$', TopicView.as_view(), name='topic'),
    url('^topic/(?P<pk>\d+)/stick/$', StickTopicView.as_view(),
        name='stick_topic'),
    url('^topic/(?P<pk>\d+)/unstick/$', UnstickTopicView.as_view(),
        name='unstick_topic'),
    url('^topic/(?P<pk>\d+)/close/$', CloseTopicView.as_view(),
        name='close_topic'),
    url('^topic/(?P<pk>\d+)/open/$', OpenTopicView.as_view(),
        name='open_topic'),
    url('^topic/(?P<pk>\d+)/poll_vote/$', TopicPollVoteView.as_view(),
        name='topic_poll_vote'),
    url('^topic/(?P<pk>\d+)/cancel_poll_vote/$', topic_cancel_poll_vote,
        name='topic_cancel_poll_vote'),
    url('^topic/latest/$', LatestTopicsView.as_view(), name='topic_latest'),

    # Add topic/post
    url('^forum/(?P<forum_id>\d+)/topic/add/$', AddPostView.as_view(),
        name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/post/add/$', AddPostView.as_view(),
        name='add_post'),

    # Post
    url('^post/(?P<pk>\d+)/$', PostView.as_view(), name='post'),
    url('^post/(?P<pk>\d+)/edit/$', EditPostView.as_view(), name='edit_post'),
    url('^post/(?P<pk>\d+)/move/$', MovePostView.as_view(), name='move_post'),
    url('^post/(?P<pk>\d+)/delete/$', DeletePostView.as_view(),
        name='delete_post'),
    url('^post/(?P<pk>\d+)/moderate/$', ModeratePost.as_view(),
        name='moderate_post'),

    # Attachment
    # url('^attachment/(\w+)/$', 'show_attachment', name='pybb_attachment'),

    # Subscription
    url('^subscription/topic/(\d+)/delete/$',
        delete_subscription, name='delete_subscription'),
    url('^subscription/topic/(\d+)/add/$',
        add_subscription, name='add_subscription'),
    url('^subscription/forum/(?P<pk>\d+)/$',
        ForumSubscriptionView.as_view(), name='forum_subscription'),

    # API
    url('^api/post_ajax_preview/$', post_ajax_preview,
        name='post_ajax_preview'),

    # Commands
    url('^mark_all_as_read/$', mark_all_as_read, name='mark_all_as_read')
]

if PYBB_NICE_URL:
    urlpatterns += [
        url(r'^c/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
        url(r'^c/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            ForumView.as_view(),
            name='forum'),
        url(
            r'^c/(?P<category_slug>[\w-]+)/(?P<forum_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            TopicView.as_view(), name='topic'),
    ]

forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import re
import inspect

import django
from django import forms
from django.core.exceptions import FieldError, PermissionDenied
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from django.utils.decorators import method_decorator
from django.utils.text import Truncator
from django.utils.translation import ugettext, ugettext_lazy
from django.utils.timezone import now as tznow
from django.utils.translation import ugettext as _

from pybb import compat, defaults, util, permissions
from pybb.models import Topic, Post, Attachment, PollAnswer, \
    ForumSubscription, Category, Forum, create_or_check_slug


User = compat.get_user_model()
username_field = compat.get_username_field()


class AttachmentForm(forms.ModelForm):
    class Meta(object):
        model = Attachment
        fields = ('file', )

    def clean_file(self):
        if self.cleaned_data['file'].size > defaults.PYBB_ATTACHMENT_SIZE_LIMIT:
            raise forms.ValidationError(ugettext('Attachment is too big'))
        return self.cleaned_data['file']

AttachmentFormSet = inlineformset_factory(Post, Attachment, extra=1, form=AttachmentForm)


class PollAnswerForm(forms.ModelForm):
    class Meta:
        model = PollAnswer
        fields = ('text', )


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', )


class BasePollAnswerFormset(BaseInlineFormSet):
    def clean(self):
        forms_cnt = (len(self.initial_forms) + len([form for form in self.extra_forms if form.has_changed()]) -
                     len(self.deleted_forms))
        if forms_cnt > defaults.PYBB_POLL_MAX_ANSWERS:
            raise forms.ValidationError(
                ugettext('You can''t add more than %s answers for poll' % defaults.PYBB_POLL_MAX_ANSWERS))
        if forms_cnt < 2:
            raise forms.ValidationError(ugettext('Add two or more answers for this poll'))


PollAnswerFormSet = inlineformset_factory(Topic, PollAnswer, extra=2, max_num=defaults.PYBB_POLL_MAX_ANSWERS,
                                          form=PollAnswerForm, formset=BasePollAnswerFormset)


class PostForm(forms.ModelForm):
    name = forms.CharField(label=ugettext_lazy('Subject'), widget=forms.TextInput(attrs={'class': 'white-back'}))
    poll_type = forms.TypedChoiceField(label=ugettext_lazy('Poll type'), choices=Topic.POLL_TYPE_CHOICES, coerce=int)
    poll_question = forms.CharField(
        label=ugettext_lazy('Poll question'),
        required=False,
        widget=forms.Textarea(attrs={'class': 'no-markitup'}))
    slug = forms.CharField(label=ugettext_lazy('Topic slug'), required=False)

    class Meta(object):
        model = Post
        fields = ('body',)
        widgets = {
            'body': util.get_markup_engine().get_widget_cls(),
        }

    def __init__(self, *args, **kwargs):
        # Move args to kwargs
        if args:
            kwargs.update(dict(zip(inspect.getargspec(super(PostForm, self).__init__)[0][1:], args)))
        self.user = kwargs.pop('user', None)
        self.ip = kwargs.pop('ip', None)
        self.topic = kwargs.pop('topic', None)
        self.forum = kwargs.pop('forum', None)
        self.may_create_poll = kwargs.pop('may_create_poll', True)
        self.may_edit_topic_slug = kwargs.pop('may_edit_topic_slug', False)
        if not (self.topic or self.forum or ('instance' in kwargs)):
            raise ValueError('You should provide topic, forum or instance')
            # Handle topic subject, poll type and question if editing topic head
        if kwargs.get('instance', None) and (kwargs['instance'].topic.head == kwargs['instance']):
            kwargs.setdefault('initial', {})['name'] = kwargs['instance'].topic.name
            kwargs.setdefault('initial', {})['poll_type'] = kwargs['instance'].topic.poll_type
            kwargs.setdefault('initial', {})['poll_question'] = kwargs['instance'].topic.poll_question

        super(PostForm, self).__init__(**kwargs)

        # remove topic specific fields
        if not (self.forum or (self.instance.pk and (self.instance.topic.head == self.instance))):
            del self.fields['name']
            del self.fields['poll_type']
            del self.fields['poll_question']
            del self.fields['slug']
        else:
            if not self.may_create_poll:
                del self.fields['poll_type']
                del self.fields['poll_question']
            if not self.may_edit_topic_slug:
                del self.fields['slug']

        self.available_smiles = defaults.PYBB_SMILES
        self.smiles_prefix = defaults.PYBB_SMILES_PREFIX

    def clean_body(self):
        body = self.cleaned_data['body']
        user = self.user or self.instance.user
        if defaults.PYBB_BODY_VALIDATOR:
            defaults.PYBB_BODY_VALIDATOR(user, body)

        for cleaner in defaults.PYBB_BODY_CLEANERS:
            body = util.get_body_cleaner(cleaner)(user, body)
        return body

    def clean(self):
        poll_type = self.cleaned_data.get('poll_type', None)
        poll_question = self.cleaned_data.get('poll_question', None)
        if poll_type is not None and poll_type != Topic.POLL_TYPE_NONE and not poll_question:
            raise forms.ValidationError(ugettext('Poll''s question is required when adding a poll'))

        return self.cleaned_data

    def save(self, commit=True):
        if self.instance.pk:
            post = super(PostForm, self).save(commit=False)
            if self.user:
                post.user = self.user
            if post.topic.head == post:
                post.topic.name = self.cleaned_data['name']
                if self.may_create_poll:
                    post.topic.poll_type = self.cleaned_data['poll_type']
                    post.topic.poll_question = self.cleaned_data['poll_question']
                post.topic.updated = tznow()
                if commit:
                    post.topic.save()
            post.updated = tznow()
            if commit:
                post.save()
            return post, post.topic

        allow_post = True
        if defaults.PYBB_PREMODERATION:
            allow_post = defaults.PYBB_PREMODERATION(self.user, self.cleaned_data['body'])
        if self.forum:
            topic = Topic(
                forum=self.forum,
                user=self.user,
                name=self.cleaned_data['name'],
                poll_type=self.cleaned_data.get('poll_type', Topic.POLL_TYPE_NONE),
                poll_question=self.cleaned_data.get('poll_question', None),
                slug=self.cleaned_data.get('slug', None),
            )
            if not allow_post:
                topic.on_moderation = True
        else:
            topic = self.topic
        post = Post(user=self.user, user_ip=self.ip, body=self.cleaned_data['body'])
        if not allow_post:
            post.on_moderation = True
        if commit:
            topic.save()
            post.topic = topic
            post.save()
        return post, topic


class MovePostForm(forms.Form):

    def __init__(self, instance, user, *args, **kwargs):
        super(MovePostForm, self).__init__(*args, **kwargs)
        self.instance = instance
        self.user = user
        self.post = self.instance
        self.category, self.forum, self.topic = self.post.get_parents()

        if not self.post.is_topic_head:
            # we do not move an entire topic but a part of it's posts. Let's select those posts.
            self.posts_to_move = Post.objects.filter(created__gte=self.post.created,
                                                     topic=self.topic).order_by('created', 'pk')
            # if multiple posts exists with the same created datetime, it's important to keep the
            # same order and do not move some posts which could be "before" our post.
            # We can not just filter by adding `pk__gt=self.post.pk` because we could exclude
            # some posts if for some reasons, a lesser pk has a greater "created" datetime
            # Most of the time, we just do one extra request to be sure the first post is
            # the wanted one
            first_pk = self.posts_to_move.values_list('pk', flat=True)[0]
            while first_pk != self.post.pk:
                self.posts_to_move = self.posts_to_move.exclude(pk=first_pk)
                first_pk = self.posts_to_move.values_list('pk', flat=True)[0]

            i = 0
            choices = []
            for post in self.posts_to_move[1:]:  # all except the current one
                i += 1
                bvars = {'author': util.get_pybb_profile(post.user).get_display_name(),
                         'abstract': Truncator(post.body_text).words(8),
                         'i': i}
                label = _('%(i)d (%(author)s: "%(abstract)s")') % bvars
                choices.append((i, label))
            choices.insert(0, (0, _('None')))
            choices.insert(0, (-1, _('All')))
            self.fields['number'] = forms.TypedChoiceField(
                label=ugettext_lazy('Number of following posts to move with'),
                choices=choices, required=True, coerce=int,
            )
            # we move the entire topic, so we want to change it's forum.
            # So, let's exclude the current one

        # get all forum where we can move this post (and the others)
        move_to_forums = permissions.perms.filter_forums(self.user, Forum.objects.all())
        if self.post.is_topic_head:
            # we move the entire topic, so we want to change it's forum.
            # So, let's exclude the current one
            move_to_forums = move_to_forums.exclude(pk=self.forum.pk)
        last_cat_pk = None
        choices = []
        for forum in move_to_forums.order_by('category__position', 'position', 'name'):
            if not permissions.perms.may_create_topic(self.user, forum):
                continue

templates/pybb/_button_new_topic.html
{% load i18n %}

<!--<a href="{% url 'pybb:add_topic' forum.id %}" class="new-topic btn btn-primary">{% trans 'New topic' %}</a>
    -->


            <a style="color:black; text-decoration: none; background-color: none;" href="{% url 'pybb:add_topic' forum.id %}"> <p style="margin-left:50px;"> <span style="color: #167ED8; font-size:12" class="icon-plus"> </span> New Topic </p><a>

templates/pybb/_button_submit.html
{% load i18n %}
<input type="submit" class="btn btn-primary" style="background-color:#428bca !important" value="{% if submit_text %}{{ submit_text }}{% else %}{% trans 'Submit' %}{% endif %}" />

templates/pybb/_easy_thumbnail_avatar.html
{% load thumbnail %}
{% thumbnail user_profile.avatar|default:PYBB_DEFAULT_AVATAR_URL PYBB_AVATAR_DIMENSIONS as avatar %}
<img src="{{ avatar.url }}" alt="{{ user_profile.get_display_name }} avatar"/>

templates/pybb/base.html
{% extends PYBB_TEMPLATE|default:"base.html" %}

{% load i18n pybb_tags %}
{% block title %}{{ PYBB_DEFAULT_TITLE }}{% endblock title %}

{% block extra_head %}
    {{ block.super }}
    <!-- Feeds -->
    <link rel="alternate" type="application/atom+xml" href="{% url 'pybb:feed_posts' %}" title="{% trans 'Latest posts on forum' %}" >
    <link rel="alternate" type="application/atom+xml" href="{% url 'pybb:feed_topics' %}" title="{% trans 'Latest topics on forum' %}" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css" integrity="sha384-v2Tw72dyUXeU3y4aM2Y0tBJQkGfplr39mxZqlTBDUZAb9BGoC40+rdFCG0m10lXk" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/fontawesome.css" integrity="sha384-q3jl8XQu1OpdLgGFvNRnPdj5VIlCvgsDQTQB6owSOHWlAurxul7f+JpUOVdAiJ5P" crossorigin="anonymous">
{% endblock %}


{% block content %}{% endblock content %}

{% block breadcrumb %}
    {% include "pybb/breadcrumb.html" %}
{% endblock %}

templates/pybb/breadcrumb.html
{% load i18n pybb_tags %}
<style>
a{
    color: #428bca;
}

a:hover{
    color: #428bca;
}
</style>
<ul class="breadcrumb" style="margin-left: -10px !important;background-color: #fafafa !important;font-size: 12px;">
    {% include "pybb/breadcrumb_top_extra_crumb.html" %}
    <li><a href="{% url 'pybb:index' %}">{% trans 'Home' %}</a> <span class="divider">/</span></li>
    {% if object %}
        {% if object.get_parents %}
            {% for obj in object.get_parents %}
                <li>{% pybb_link obj %} <span class="divider">/</span></li>
            {% endfor %}
        {% endif %}
        {% if extra_crumb %}
            <li>{% pybb_link object %} <span class="divider">/</span></li>
        {% else %}
            <li>{{ object }}</li>
        {% endif %}
    {% endif %}
    {% if extra_crumb %}
        <li>{% trans extra_crumb %}</li>
    {% endif %}
</ul>

templates/pybb/delete_post.html
{% extends 'pybb/base.html' %}
{% load i18n pybb_tags %}

{% block content %}
    <h1>{% trans 'Are you sure you want to delete this message?' %}</h1>
    <div class="post-preview well">
        {{ post.body_html|safe }}
    </div>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class="btn" href="{{ post.get_absolute_url }}">← {% trans 'No, take me back' %}</a>
            <input type="submit" class="btn btn-danger" value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock content %}

templates/pybb/edit_profile.html
{% extends 'pybb/base.html' %}

{% load i18n pybb_tags %}

{% block title %}{% trans 'Profile editing' %}{% endblock title %}

{% block content %}
    <h1>{% trans 'Profile editing' %}</h1>
    {% include 'pybb/avatar.html' with user=user %}
    <form method="post" enctype="multipart/form-data" class="profile-edit">
        {% csrf_token %}
        <fieldset>
            <legend>{% trans 'Profile editing' %}</legend>
            {% include "pybb/form.html" %}
            <p>{% include "pybb/_button_save.html" %}</p>
        </fieldset>
    </form>
    <h1>{% trans 'Subscriptions on topics' %}</h1>
    <ul>
        {% for sub in user.subscriptions.all %}
            <li>
                {% pybb_link sub %}
                &mdash;
                <strong>
                    <a href="{% url 'pybb:delete_subscription' sub.id %}">{% trans 'delete' %}</a>
                </strong>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/pybb/forum.html
{% extends 'pybb/base.html' %}
{% load pybb_tags i18n %}

{% block title %}{{ forum.name }}{% endblock title %}


{% block content %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css" integrity="sha384-v2Tw72dyUXeU3y4aM2Y0tBJQkGfplr39mxZqlTBDUZAb9BGoC40+rdFCG0m10lXk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/fontawesome.css" integrity="sha384-q3jl8XQu1OpdLgGFvNRnPdj5VIlCvgsDQTQB6owSOHWlAurxul7f+JpUOVdAiJ5P" crossorigin="anonymous">



        <div class="py-5">
        <div class="">


     <div class="medium-24 column" style="padding: 0">


        <h2 class="setting-header" style="color: #222; cursor: auto; font-style: normal; line-height: 1;font-size: 24px; font-weight: lighter;">{{ forum.name }}
       <a href="{% url 'pybb:add_topic' forum.id %}" class="add-button" style="background-color: #167ED8; right: 0"><span class="icon-plus" style="display: flex;justify-content: center;align-items: center;font-size: 20px;margin-left: 1px;"></span></a>
        </h2>
        </div>
        {% if forum.headline %}
            <div class="forum-headline alert alert-block">
                {{ forum.headline|safe }}
            </div>
        {% endif %}

        {% include "pybb/pagination.html" %}

        {% include 'pybb/forum_list.html' with forum_list=forum.forums_accessed category='' parent_forum=forum %}

        {% include "pybb/topic_list.html" %}

        {% include "pybb/pagination.html" %}

        <div class="controls">
            {% if user|pybb_may_create_topic:forum %}
                {% include "pybb/_button_new_topic.html" %}
            {% endif %}
            {% include "pybb/_button_forum_subscription.html" %}
        </div>
    </div>

        </div>


{% endblock content %}

{% block breadcrumb %}
    {% with forum as object %}
        {% include "pybb/breadcrumb.html" %}
    {% endwith %}
{% endblock %}

templates/pybb/index.html
{% extends 'pybb/base.html' %}

{% load i18n %}

{% block title %}{{ PYBB_DEFAULT_TITLE }}{% endblock title %}

{% block breadcrumb %}
    {% with extra_crumb="Forum" %}{% include "pybb/breadcrumb.html" %}{% endwith %}
{% endblock %}

{% block content %}
    {% if categories %}
        {% for category in categories %}
            {% include 'pybb/category.html' %}
        {% endfor %}
    {% else %}
        <h2>{% trans 'Forum categories are not created' %}</h2>
        <a href="{% url 'admin:pybb_category_add' %}">{% trans 'Add a category now' %}</a>
    {% endif %}
    {% if user.is_authenticated %}
        <div id="mark-all-as-read">
            <a href="{% url 'pybb:topic_latest' %}">{% trans 'Last updates in topics' %}</a> /
            <a href="{% url 'pybb:mark_all_as_read' %}">{% trans 'Mark all forums as read' %}</a>
        </div>
    {% endif %}
{% endblock content %}

templates/pybb/poll_edit_form.html
{% load i18n %}

{% include "pybb/form_field.html" with field=form.poll_type %}
<div id="poll-question">
  {% include "pybb/form_field.html" with field=form.poll_question %}
</div>
<div id="poll-answers-formset" style="display: none;">
  <br>{% trans 'Poll answers' %}
    {% include "pybb/form_errors.html" with form=pollformset %}
    {% for form_answer in pollformset %}
        <div class="poll-answer-form">
            {% include "pybb/form.html" with form=form_answer hide_labels=1 %}
        </div>
    {% endfor %}
  {{ pollformset.management_form }}
</div>

<script type="text/javascript">
  window.onload = function () {
    $('div#poll-answers-formset div.poll-answer-form').formset({
      deleteText:'{% trans "remove answer" as txt %}{{ txt|escapejs }}',
      addText:'{% trans "add answer" as txt %}{{ txt|escapejs }}',
      prefix: 'poll_answers'
    });

    var toggle_poll_answers_formset = function (poll_type) {
      if (poll_type === "0") {
        $('div#poll-answers-formset').hide();
        $('div#poll-question').hide();
      } else {
        $('div#poll-answers-formset').show();
        $('div#poll-question').show();
      }
    };

    $('#id_poll_type').each(function () {
      toggle_poll_answers_formset($(this).val());
    }).change(function () {
      toggle_poll_answers_formset($(this).val());
    });
  };

</script>

templates/pybb/post_template.html
{% load i18n pybb_tags staticfiles %}

{% pybb_get_profile user=post.user as post_user_profile %}
{% pybb_get_profile user=user as user_profile %}


    <tr class="post-row" style="background-color: white !important;">
        <td class="post-info" style="display: flex;align-items: center;">
            {% include "pybb/avatar.html" with user=post.user %}
            <span style="font-weight:bold; margin-left:20px; font-size:13px; width: 150px; margin-right: 8vw;">{{ post_user_profile.get_first_last }} <br/> <span style="font-size:12px; font-weight:lighter; font-style: italic; color: gray">{% pybb_time topic.updated %}</span></span>
        </td>
        <td>

            <!-- <div class="post-author">
                <span style="font-weight:bold;">{{ post_user_profile.get_first_last }}</span> -->
                <!--<a href="{{ post_user_profile.get_absolute_url }}"> -->
                    <!-- <span class="post-username" style="font-weight:lighter;">{{ post_user_profile.get_display_name }}</span> -->
                <!-- </a> -->


            <!-- </div> -->
            {% if post_user_profile.rank %}
                <div class="rank">
                    {% blocktrans with rank=post_user_profile.rank %}Rank: {{ rank }}{% endblocktrans %}
                    {% if user.is_authenticated and user != post.user %}
                        <a href="#" class="vote" rel="{{ post_user_profile.get_vote_up_url }}">+</a>
                        <a href="#" class="vote" rel="{{ post_user_profile.get_vote_down_url }}">-</a>
                    {% endif %}
                </div>
            {% endif %}

            {% comment %}
            <div class="post-controls">
                {% if user|pybb_may_edit_post:post %}
                    <a href="{% url 'pybb:edit_post' pk=post.id %}">{% trans 'Edit' %}</a>
                {% endif %}
                {% if user|pybb_may_delete_post:post %}
                    <a onclick="pybb_delete_post('{% url 'pybb:delete_post' post.id %}',
                            'post-{{ post.id }}', '{% trans 'Delete post?' as txt %}{{ txt|escapejs }}'); return false;"
                       href="{% url 'pybb:delete_post' post.id %}">{% trans 'Delete' %}</a>
                {% endif %}
                {% if post.on_moderation and user.is_moderator %}
                    <a href="{% url 'pybb:moderate_post' pk=post.id %}">{% trans 'Approve post' %}</a>
                {% endif %}
                {% if user.is_moderator %}
                    <a href="{% url 'pybb:move_post' pk=post.id %}">{% if post.is_topic_head %}{% trans 'Move' %}{% else %}{% trans "Split" %}{% endif %}</a>
                {% endif %}

                {% if user|pybb_may_admin_post:post %}
                    <a href="{% url 'admin:pybb_post_change' post.id %}">{% trans 'Admin' %}</a>
                {% endif %}

            </div>
            {% endcomment %}
        </td>
        <td style="padding-top: 30px;">
            <div class="d-inline" style="background-color:#22EA7F; color:white; padding-top:11px; padding-bottom: 11px; padding-right: 20px; padding-left: 20px; margin-left:-50px; margin-right:20px;">  {{ topic.name.0 | upper }}  </div>
        </td>
        <td class="post-content" style="font-size: 12px;width: 70%; vertical-align: middle;">
            {{ post.body_html|safe }}

            {% if not user.is_authenticated or user_profile.show_signatures %}
                {% if post_user_profile.signature %}
                    <div class="post-signature">
                        {{ post_user_profile.signature_html|safe }}
                    </div>
                {% endif %}
            {% endif %}

            <!--
            {% if post.updated %}
                <div class="updated-message">{% trans 'Edited' %} {% pybb_time post.updated %}</div>
            {% endif %}
        -->

            {% comment %}
                    {% if post.attachment_cache %}
                    {% for attach in post.attachment_cache %}
                    <br/>
                    {% trans 'Attachment' %}{% trans ':' %} <a href="{{ attach.get_absolute_url }}">{{ attach.name }}</a> ({{ attach.size_display }})
                    {% endfor %}
                    {% endif %}
            {% endcomment %}

            <!--
            <div class="post-related">
                {% if user|pybb_may_create_post:post.topic %}
                    <a href="{% url 'pybb:add_post' topic.id %}?quote_id={{ post.id }}" class="quote-link">{% trans 'quote' %}</a>
                    <a href="#" class="quote-selected-link">{% trans 'quote selected' %}</a>
                {% endif %}
                <div class="attachments">
                    {% for attachment in post.attachments.all %}
                        <a href="{{ attachment.file.url }}"><img src="{% static 'pybb/img/attachment.png' %}"> {{ attachment.size_display }}</a>
                    {% endfor %}
                </div>
            </div>
        -->
        </td>
    </tr>

    <style>
    .form_bdy {
      background-color: white !important;
      border: 2px solid lightgray;
    }
    .field_label {
      display: none;
    }
    textarea {
      margin: 0 !important;
      height: 150px !important;
    }
    </style>